import Head from "next/head";
import HomeSection from "../sections/HomeSection";
import WhoWeAreSection from "../sections/WhoWeAreSection";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Onend Solutions</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<HomeSection />
			<WhoWeAreSection />
		</div>
	);
}
