import Head from "next/head";
import HomeSection from "../sections/HomeSection";
import WhoWeAreSection from "../sections/WhoWeAreSection";
import { createClient } from "next-sanity";

export default function Home({ homeSectionData, whoWeAreSectionData }) {
	const homeSection = homeSectionData[0];
	const whoWeAreSection = whoWeAreSectionData[0];
	return (
		<div>
			<Head>
				<title>Onend Solutions</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<HomeSection data={homeSection} />
			<WhoWeAreSection data={whoWeAreSection} />
		</div>
	);
}

export const getServerSideProps = async () => {
	const client = createClient({
		dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
		projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
		useCdn: true,
	});
	const query = "*[_type == 'homeSection']";
	const homeSectionData = await client.fetch(query);
	const query1 = "*[_type == 'whoWeAreSection']";
	const whoWeAreSectionData = await client.fetch(query1);
	return {
		props: {
			homeSectionData,
			whoWeAreSectionData,
		},
	};
};
